<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./scene.glb
Author: Woolvz (https://sketchfab.com/Woolvz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-house-10ad02c990af4334847b94b34d033b77
Title: Cyberpunk House
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	export const ref = new Group();

	const gltf = useGltf('./models/cyberpunk-house.glb');

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group rotation={[-Math.PI / 2, 0, 0]}>
			<T.Group rotation={[Math.PI / 2, 0, 0]}>
				<T.Mesh geometry={gltf.nodes.defaultMaterial.geometry} material={gltf.materials.blinn45} />
				<T.Mesh
					geometry={gltf.nodes.defaultMaterial_1.geometry}
					material={gltf.materials.lambert1}
				/>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
