<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./cyberpunk-store.glb
Author: NickJArt (https://sketchfab.com/NickJArt)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/247-cyberpunk-store-2fff8b3c264e49d8a502918abea114b3
Title: 24/7 Cyberpunk Store
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers, useLoader } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import TVMonitor from './tv.svelte';

	export const ref = new Group();

	const gltf = useGltf('./models/cyberpunk-store.glb');

	const component = forwardEventHandlers();

	const parentHandleClick = () => {
		console.log('HELLO from Parent!');
	};
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group rotation={[-Math.PI / 2, 0, 0]} scale={2.24}>
			<T.Group rotation={[Math.PI / 2, 0, 0]}>
				<T.Mesh geometry={gltf.nodes.Object_4.geometry} material={gltf.materials['Default.001']} />
				<T.Mesh geometry={gltf.nodes.Object_6.geometry} material={gltf.materials['Default.002']} />
				<T.Mesh
					geometry={gltf.nodes.Object_8.geometry}
					material={gltf.materials['Material.001']}
					position={[-0.13, -1.01, -0.09]}
					rotation={[0, 1.56, 0]}
					scale={[2.01, 1, 2.05]}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_10.geometry}
					material={gltf.materials['Material.002']}
					position={[2.39, -1.05, -0.41]}
					rotation={[-Math.PI, 1.21, -Math.PI]}
					scale={[8, 1, 8]}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_12.geometry}
					material={gltf.materials['0G_Steel_Galvanized_mqm']}
					position={[0.6, 0.2, -1.78]}
					rotation={[-Math.PI, 1.21, -Math.PI]}
					scale={0.48}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_12.geometry}
					material={gltf.materials['0G_Steel_Galvanized_mqm']}
					position={[-0.17, 0.2, -2.32]}
					rotation={[-Math.PI, 0.03, -Math.PI]}
					scale={0.48}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_12.geometry}
					material={gltf.materials['0G_Steel_Galvanized_mqm']}
					position={[-1.14, 0.2, -2.345]}
					rotation={[-Math.PI, 0.03, -Math.PI]}
					scale={0.48}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_14.geometry}
					material={gltf.materials['0G_Steel_Galvanized_mqm']}
					position={[1.5, 0.2, 0.54]}
					rotation={[-Math.PI, 1.21, -Math.PI]}
					scale={0.48}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_16.geometry}
					material={gltf.materials['0G_Steel_Galvanized_mqm']}
					position={[1.84, 0.2, 1.46]}
					rotation={[-Math.PI, 1.21, -Math.PI]}
					scale={0.48}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_18.geometry}
					material={gltf.materials.Material}
					position={[1.2, -0.01, 0.46]}
					rotation={[-Math.PI, 0.55, -Math.PI]}
					scale={0.43}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_20.geometry}
					material={gltf.materials['0G_Steel_Galvanized_mqm']}
					position={[1.2, -0.01, 0.46]}
					rotation={[-Math.PI, 0.55, -Math.PI]}
					scale={0.43}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_22.geometry}
					material={gltf.materials['6B_Plastic_Matte_mqm_Black']}
					position={[1.2, -0.01, 0.46]}
					rotation={[-Math.PI, 0.55, -Math.PI]}
					scale={0.43}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_24.geometry}
					material={gltf.materials['6B_Plastic_Matte_mqm_Black']}
					position={[1.2, -0.01, 0.46]}
					rotation={[-Math.PI, 0.55, -Math.PI]}
					scale={0.43}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_26.geometry}
					material={gltf.materials['7C_Glass_Frosted_mqm']}
					position={[1.2, -0.01, 0.46]}
					rotation={[-Math.PI, 0.55, -Math.PI]}
					scale={0.43}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_28.geometry}
					material={gltf.materials.Light_Traffic_White_tqm}
					position={[1.2, -0.01, 0.46]}
					rotation={[-Math.PI, 0.55, -Math.PI]}
					scale={0.43}
				/>
				<TVMonitor on:click={parentHandleClick} />
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
