<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./lamp.glb
Author: Invisiprim (https://sketchfab.com/invisiprim3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-lamps-764e16f3da6d477cbedf193f8d7cbaf6
Title: Sci-fi Lamps
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	export const ref = new Group();

	const gltf = useGltf('./models/lamp.glb');

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group scale={0.01}>
			<T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
				<T.Mesh geometry={gltf.nodes.lamp1_shell_0.geometry} material={gltf.materials.shell} />
				<T.Mesh geometry={gltf.nodes.lamp1_glass_0.geometry} material={gltf.materials.glass} />
				<T.Mesh geometry={gltf.nodes.lamp1_parts1_0.geometry} material={gltf.materials.parts1} />
			</T.Group>
			<T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
				<T.Mesh geometry={gltf.nodes.lamp3_parts2_0.geometry} material={gltf.materials.parts2} />
				<T.Mesh geometry={gltf.nodes.lamp3_shell_0.geometry} material={gltf.materials.shell} />
				<T.Mesh geometry={gltf.nodes.lamp3_glass_0.geometry} material={gltf.materials.glass} />
				<T.Mesh geometry={gltf.nodes.lamp3_parts1_0.geometry} material={gltf.materials.parts1} />
			</T.Group>
			<T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
				<T.Mesh geometry={gltf.nodes.lamp2_parts2_0.geometry} material={gltf.materials.parts2} />
				<T.Mesh geometry={gltf.nodes.lamp2_shell_0.geometry} material={gltf.materials.shell} />
				<T.Mesh geometry={gltf.nodes.lamp2_glass_0.geometry} material={gltf.materials.glass} />
				<T.Mesh geometry={gltf.nodes.lamp2_parts1_0.geometry} material={gltf.materials.parts1} />
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
